<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hand">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <xacro:macro name="hand" params="connected_to:='' arm_id:='panda' rpy:='0 0 0' xyz:='0 0 0' safety_distance:=0">
    <xacro:unless value="${connected_to == ''}">
      <joint name="${arm_id}_hand_joint" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${arm_id}_hand"/>
        <origin xyz="${xyz}" rpy="${rpy}"/>
      </joint>
    </xacro:unless>
    <link name="${arm_id}_hand">
      <visual>
        <origin xyz="0 0 0" rpy="0 ${pi} 0"/>
        <geometry>
          <mesh filename="package://franka_description/meshes/visual/pump_simplified.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0.05" rpy="0 0 ${pi/2}"/>
        <geometry>
          <cylinder radius="${0.05+safety_distance}" length="0.12" />
        </geometry>
      </collision>
    </link>
   <!-- Define the hand_tcp frame -->
    <link name="${arm_id}_hand_tcp" />
    <joint name="${arm_id}_hand_tcp_joint" type="fixed">
      <origin xyz="0 0 0.113" rpy="0 0 0" />
      <parent link="${arm_id}_hand" />
      <child link="${arm_id}_hand_tcp" />
    </joint>
  </xacro:macro>
</robot>
